---
title: "ComputingTwoProject"
author: "Abigail McPheeters"
date: "4/16/2020"
output: html_document
---




Abi's Section

Photoresistor to record light and teh time that elapses when there is light versus no light. This was to be used in a greenhuose to measure teh amount of light in a day to compare with heat to see if tehre was a correlation with plant growth. 

```{r}
#photoresistor code from www.elegoo.com 
int lightPin = 0;
int latchPin = 11;
int clockPin = 9;
int dataPin = 12;

int leds = 0;

void setup() 
{ 
  pinMode(latchPin, OUTPUT);
  pinMode(dataPin, OUTPUT);  
  pinMode(clockPin, OUTPUT);
}
void updateShiftRegister()
{
   digitalWrite(latchPin, LOW);
   shiftOut(dataPin, clockPin, LSBFIRST, leds);
   digitalWrite(latchPin, HIGH);
}
void loop() 
{
  int reading  = analogRead(lightPin);
  int numLEDSLit = reading / 57;  //1023 / 9 / 2
  if (numLEDSLit > 8) numLEDSLit = 8;
  leds = 0;   // no LEDs lit to start
  for (int i = 0; i < numLEDSLit; i++)
  {
    leds = leds + (1 << i);  // sets the i'th bit
  }
  updateShiftRegister();
}

#this code is in the works and needs to be tested with the Elegoo Photoresistor before alterations. It may only be compatible with a Raspberry Pi or Arduino set up
```

Abi's Resources
```{r}
#resources

resources <- matrix(c("https://www.elegoo.com/download/","https://startingelectronics.org/tutorials/arduino/modules/photo-resistor/","https://www.r-bloggers.com/timing-in-r/","https://www.cyclismo.org/tutorial/R/tables.html"),ncol=1,byrow=TRUE)
colnames(resources) <- c("Source")
rownames(resources) <- c("Photoresistor Code:","More on Photoresistors:","Timing Coding:","Table Code:")
resources <- as.table(resources)
resources
```
